trigger:
  branches:
    include:
      - "*"

strategy:
  matrix:
    mac:
      imageName: "macos-10.15"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.15.x"
    displayName: "Install Node.js"

  - bash: |
      echo ">>> Validate swift environment"
      swift test --package-path test-packages/basic
    displayName: "Validate swift is installed and working"

  - bash: |
      echo ">>> Installing deps"
      yarn install
      echo ">>> Compile vscode-test"
      yarn test
    displayName: Run Tests
