name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Validate swift environment
        run: swift test --package-path test-packages/basic

      - name: Install yarn packages
        run: yarn install --frozen-lockfile

      - run: yarn test
